# Generated by Django 3.0.4 on 2020-03-27 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_inventory_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('id_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Inventory')),
            ],
        ),
    ]
